---
title: "ProblemSet3"
author: "Anna Li"
date: "March 15, 2015"
output: html_document
---

# 1. Explore dataset 
```{r}
library(ggplot2)
data(diamonds) # diamonds dataset comes from ggplot2
summary(diamonds)
diamonds$color # prints out the colors for diamonds data set. 
# Levels: D < E < F < G < H < I < J signals the ordering of data
# Learn about diamonds dataset
?diamonds
```

# 2. Price Histogram

```{r, echo=FALSE}
# Create a histogram of the price of
# all the diamonds in the diamond data set.

# TYPE YOUR CODE BELOW THE LINE
# =======================================
names(diamonds)
ggplot(aes(x = price), data = diamonds) +
    geom_histogram()
```

# 3. Price Histogram Summary

```{r}
summary(diamonds$price)
```

# 4. Diamond Counts
```{r}
summary(diamonds$price < 500)
summary(diamonds$price < 250)
summary(diamonds$price >= 15000)
```
1729, 0 , 1656

5. Cheaper Diamonds

```{r}
# Explore the largest peak in the
# price histogram you created earlier.

# Try limiting the x-axis, altering the bin width,
# and setting different breaks on the x-axis.

# There won’t be a solution video for this
# question so go to the discussions to
# share your thoughts and discover
# what other people find.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Submit your final code when you are ready.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================================
ggplot(aes(x = price), data = diamonds) +
    geom_histogram(binwidth = 50, color = 'black', fill = '#099DD9') +
    scale_x_continuous(lim = c(0, 2500))
    
```

# 6. Price by Cut Histograms & 7. Price by Cut
```{r}
# Break out the histogram of diamond prices by cut.

# You should have five histograms in separate
# panels on your resulting plot.

# TYPE YOUR CODE BELOW THE LINE
# ======================================================
ggplot(aes(x = price), data = diamonds) +
    geom_histogram(binwidth = 500, color = 'black', fill = '#099DD9') +
    facet_wrap(~cut)
by(diamonds$price, diamonds$cut, summary)

by(diamonds$price, diamonds$cut, max)
```

# 8. Scales and Multiple Histograms
```{r}
# In the two last exercises, we looked at
# the distribution for diamonds by cut.

# Run the code below in R Studio to generate
# the histogram as a reminder.

# ===============================================================

qplot(x = price, data = diamonds) + facet_wrap(~cut, scales = 'free_y')
                                                                               
# ===============================================================

# In the last exercise, we looked at the summary statistics
# for diamond price by cut. If we look at the output table, the
# the median and quartiles are reasonably close to each other.

# diamonds$cut: Fair
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     337    2050    3282    4359    5206   18570 
# ------------------------------------------------------------------------ 
# diamonds$cut: Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     327    1145    3050    3929    5028   18790 
# ------------------------------------------------------------------------ 
# diamonds$cut: Very Good
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     336     912    2648    3982    5373   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Premium
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326    1046    3185    4584    6296   18820 
# ------------------------------------------------------------------------ 
# diamonds$cut: Ideal
#    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#     326     878    1810    3458    4678   18810 

# This means the distributions should be somewhat similar,
# but the histograms we created don't show that.

# The 'Fair' and 'Good' diamonds appear to have 
# different distributions compared to the better
# cut diamonds. They seem somewhat uniform
# on the left with long tails on the right.

# Let's look in to this more.

?facet_wrap

# Look up the documentation for facet_wrap in R Studio.
# Then, scroll back up and add a parameter to facet_wrap so that
# the y-axis in the histograms is not fixed. You want the y-axis to
# be different for each histogram.

# If you want a hint, check out the Instructor Notes.

# In ggplot
ggplot(aes(x = price), data = diamonds) +
    geom_histogram(binwidth = 500, color = 'black', fill = '#099DD9') +
    facet_wrap(~cut, scales = 'free_y')
```

# 9. Price per Carat by Cut
```{r}
# Create a histogram of price per carat
# and facet it by cut. You can make adjustments
# to the code from the previous exercise to get
# started.

# Adjust the bin width and transform the scale
# of the x-axis using log10.

# Submit your final code when you are ready.

# ENTER YOUR CODE BELOW THIS LINE.
# ===========================================================================

ggplot(aes(x = price/carat), data = diamonds) +
    geom_histogram(color = 'black', fill = '#099DD9') +
    facet_wrap(~cut, scales = 'free_y') +
    scale_x_log10()
```

# 10. Price Box Plots

```{r}
# Investigate the price of diamonds using box plots,
# numerical summaries, and one of the following categorical
# variables: cut, clarity, or color.

# There won’t be a solution video for this
# exercise so go to the discussion thread for either
# BOXPLOTS BY CLARITY, BOXPLOT BY COLOR, or BOXPLOTS BY CUT
# to share you thoughts and to
# see what other people found.

# You can save images by using the ggsave() command.
# ggsave() will save the last plot created.
# For example...
#                  qplot(x = price, data = diamonds)
#                  ggsave('priceHistogram.png')

# ggsave currently recognises the extensions eps/ps, tex (pictex),
# pdf, jpeg, tiff, png, bmp, svg and wmf (windows only).

# Copy and paste all of the code that you used for
# your investigation, and submit it when you are ready.
# =================================================================
ggplot(aes(x = cut, y = price), data = diamonds) +
    geom_boxplot()
ggplot(aes(x = clarity, y = price), data = diamonds) +
    geom_boxplot()

```
