---
title: "ResourcesUsedEDAwithR"
author: "Anna Li"
date: "March 11, 2015"
output: html_document
---

# Common & Useful R commands 
## syntax for creating R chunks in RMD
```{r}
summary(mtcars)
```


## Directories
### Find current directory
getwd()
### Move to a different directory
setwd('/Users/horsepower/Dropbox/Udacity/NanoDA/EDAwithR/EDA_Course_Materials/lesson2')
### See all files in directory
list.files()

## CSV
reddit <- read.csv('reddit.csv')
*If the file is tab separated, there are two ways to import the data:*   
reddit <- read.csv('reddit.tsv', sep='\t')
reddit <- read.delim('reddit.tsv')

## Exploring data
**Column names (in R times, see the variables)**
names(reddit)
**Find the dimensions (rows, columns)**
dim(reddit)
**Find the structure (columns, data types, example of values...)**
str(reddit)
**Print out the first 6 lines of dataframe (6 is default)**
head(reddit)
head(reddit, 3) # integer specifies only first 3 lines, use negative to last 3 lines
**Print out last 6 lines of dataframe**
tail(reddit)
tail(reddit, 10) # print out last 10 lines, can use negative integer
**Descriptive stats on data, e.g. mean, median, & quartiles **
summary(reddit)
**Find all attributes**
attributes(reddit)
**Find all column names**
colnames(reddit)
**Find all row names**
rownames(reddit)


## Basic Plotting
### qplot
qplot(x = friend_count, data = pf)
(x is the x variable you want to display in the histogram)
### ggplot 
ggplot(aes(x = friend_count), data = pf) + 
  geom_histogram()

# Resources Used in the Exploratory Data Analysis with R class

## Installation of packages
* Error around mirroring
http://stackoverflow.com/questions/16826933/installation-of-r-fpc-package
http://stackoverflow.com/questions/17705133/package-error-when-running-r-code-on-command-line

## ggplot
### Facet_wrap
http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/
### Box plot
http://stackoverflow.com/questions/21533158/remove-outliers-fully-from-multiple-boxplots-made-with-ggplot2-in-r-and-display
http://docs.ggplot2.org/0.9.3.1/geom_boxplot.html
### Frequency Polygon
http://www.inside-r.org/packages/cran/ggplot2/docs/geom_freqpoly
http://stackoverflow.com/questions/21121446/how-to-plot-in-the-same-graph-the-histogram-and-the-frequency-polygon-of-two-s
### Histograms
Free scales
http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/
### Line plots
http://docs.ggplot2.org/current/geom_line.html
http://stackoverflow.com/questions/10357768/plotting-lines-and-the-group-aesthetic-in-ggplot2
### Scale x axis
**log10**
http://forums.udacity.com/questions/100224132/error-using-scale_x_log10-with-this-data
### Scale y axis
**scale_y_continuous**
http://www.cookbook-r.com/Graphs/Axes_(ggplot2)/
### Setting labels
http://www.cookbook-r.com/Graphs/Bar_and_line_graphs_(ggplot2)/
http://www.cookbook-r.com/Graphs/Titles_(ggplot2)/
### Styling
**Add color to lines** 
http://www.cookbook-r.com/Graphs/Colors_%28ggplot2%29/

## R language syntax
### Calculate percentage statistics on a column in a dataframe
http://stackoverflow.com/questions/9623763/in-r-how-can-i-compute-percentage-statistics-on-a-column-in-a-dataframe-tabl
### Read in dataset into R
http://stackoverflow.com/questions/18161009/error-in-reading-in-data-set-in-r
http://www.statmethods.net/input/importingdata.html
#### rowSums
http://stackoverflow.com/questions/3991905/vector-that-is-sum-of-rows
http://stackoverflow.com/questions/20819100/colsum-rowsum-populating-matrix
http://www.inside-r.org/r-doc/base/colMeans
### Rename variables
http://www.statmethods.net/management/variables.html
http://stackoverflow.com/questions/7531868/how-to-rename-a-single-column-in-a-data-frame-in-r
### Substring
http://stackoverflow.com/questions/7963898/extracting-the-last-n-characters-from-a-string-in-r
### Create a dataframe from a matrix
http://stackoverflow.com/questions/15885111/create-data-frame-from-a-matrix-in-r
### Subsetting
http://stackoverflow.com/questions/8005154/conditionally-remove-dataframe-rows-with-r
### Overwrite/Replace values
http://stackoverflow.com/questions/19503266/r-replace-all-particular-values-in-a-data-frame
http://stackoverflow.com/questions/5824173/replace-a-value-in-a-data-frame-based-on-a-conditional-if-statement-in-r
### plyr library
**subsetting & deleting rows**
http://blog.rstudio.org/2014/01/17/introducing-dplyr/


# Data Wrangling Resources
Taken directly from Udacity's EDA with R course materials
https://www.udacity.com/course/viewer#!/c-ud651-nd/l-685569242/m-3552939568
> Data munging or data wrangling can take up much of a data scientist's or data analyst's time. There are 
> two R packages that make these tasks easier in R: tidyr and dplyr.

> tidyr -a package that reshapes the layout of your data

> dplyr - a package that helps you transform tidy, tabular data

> Review Data Wrangling in R to get a sense of how these packages allow you to manipulate data. You can use > these packages to help you in the next programming task and in your future investigations.
> http://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf
> http://www.rstudio.com/resources/cheatsheets/
> You may also download this useful Data Wrangling Cheat Sheet. There are some other useful cheat sheets at > RStudio. https://s3.amazonaws.com/udacity-hosted-downloads/ud651/DataWranglingWithR.pdf



